#$Id: Makefile,v 1.5 2008/04/18 02:32:59 judc Exp $
ROOT=..\..

include $(ROOT)\Rules.mak

all: 
	$(DCC) -B Step1\RegistryTest.dpr
	$(DCC) -B Step2\RegistryTest.dpr
	$(DCC) -B Step3\RegistryTest.dpr

